### PR TITLE
chore(package.json): bump versions to fix `npm audit` vulnerabilities

### PR DESCRIPTION
**Pull request by darcyparker**
* Only dev-dependencies updated

***Short description of what this resolves:***

Resolves `npm audit` issues.

***Proposed changes:***

### CODE REVIEW

**Comment by darcyparker** [comment]
Note: `npm outdated` reports a number of outdated packages too... But the focus of this pull request is to just fix npm audit vulnerabilities. (276 of 277 fixed)

**Review by thedaviddias — APPROVED** [review]
Hey @darcyparker, thanks for doing this!

**Comment by darcyparker** [comment]
@thedaviddias - NP. (For my own information, I see this is approved, but I don't have ability to merge it. (That's fine if I don't have permission...) But what is the process for merging it? Or when does it get merged?

**Comment by thedaviddias** [comment]
I will merge it now! 😉

**Pull request merged**
