### PR TITLE
docs: user-guide rules updates

### PR DESCRIPTION
**Pull request by bcdady**
***Short description of what this resolves:***
Updates a few docs with readability and examples

***Proposed changes:***
Markdown modifications to 'rules' docs

### CODE REVIEW

**Review by coliff — APPROVED** [review]

**Comment by thedaviddias** [comment]
Thanks @bcdady for these fixes!

**Review by thedaviddias — APPROVED** [review]

**Comment by bcdady** [comment]
> Thanks @bcdady for these fixes!

You're very welcome. Can you confirm the syntax in [this example](https://github.com/bcdady/HTMLHint/blob/4d6a2d314a1f37db46405ce631c4785d2b799240/docs/user-guide/rules/attr-lowercase.md#example) is correct?
I'm still having issues with this rule. Example output:
```log
L84 |... <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5...
                                                          ^ The attribute name of [ viewBox ] must be in lowercase. (attr-lowercase)
```
Maybe I should open a separate issue?

**Comment by coliff** [comment]
@bcdady - that's a known issue... ideally camelCase SVG attributes would be whitelisted.

see: https://github.com/htmlhint/HTMLHint/issues/542

**Pull request merged**
