### PR TITLE
docs: update docusaurus

### PR DESCRIPTION
**Pull request by thedaviddias**
***Short description of what this resolves:***

Update docusaurus for website

### CODE REVIEW

**Comment by nschonni** [comment]
Hard to tell with the diff on the lockfile, but it looks like `resolved` and `integrity` values are missing now

**Comment by thedaviddias** [comment]
> Hard to tell with the diff on the lockfile, but it looks like `resolved` and `integrity` values are missing now

Fixed.

**Review by nschonni — APPROVED** [review]
Haven't worked with Docusaurus before, but RSLGTM

**Comment by nschonni** [comment]
Separate from this, there should probably be a job to check, build, and publish the website

**Comment by thedaviddias** [comment]
> Separate from this, there should probably be a job to check, build, and publish the website

Yes, I'm probably create a workflow in another that only triggers when a change occurs for the website.

**Pull request merged**
