### PR TITLE
docs: create SECURITY.md

### PR DESCRIPTION
**Pull request by thedaviddias**
***Short description of what this resolves:***

Add SECURITY.md file

### CODE REVIEW

**Review by nschonni — COMMENTED** [review]
LGTM, but needs a quick prettier for the CI

**Review by nschonni — APPROVED** [review]

**Comment by thedaviddias** [comment]
> LGTM, but needs a quick prettier for the CI

Yes, I will add this in another PR.

**Comment by coliff** [comment]
> This document outlines general security procedures and policies for the GoTrustify infrastructure

what’s the GoTrustify infrastructure?

**Pull request merged**
