### PR TITLE
chore: update remaining htmlhint.io refs

### PR DESCRIPTION
**Pull request by nschonni**
***Short description of what this resolves:***
Points to the parked domain. Not sure if this will auto-deploy, but we'll see

***Proposed changes:***

### CODE REVIEW

**Review by thedaviddias — APPROVED** [review]

**Comment by nschonni** [comment]
If this doesn't update it, I'll try in https://github.com/htmlhint/htmlhint-playground

**Comment by nschonni** [comment]
Don't see a change, so I'll try the other repo

**Comment by nschonni** [comment]
https://github.com/htmlhint/htmlhint-playground/commit/fc8e20be4967bdcafd4f1e2df0221b4ea5bc596d fixed it, so I'm going to remove the playground code in this repo

**Pull request merged**
