### PR TITLE
fix 0.12.0 dist file

### PR DESCRIPTION
**Pull request by nicolashenry**
**Fixes**: #372 

#### Short description of what this resolves:
It seems that the published dist/htmlhint.js file is corrupted (not sure about the reason).

#### Proposed changes:
I just run "npm run build" to update the file.

### CODE REVIEW

**Comment by reckter** [comment]
I've been scratching my head on why this isn't loading correctly! 👍 new release imminent? :)

**Comment by thedaviddias** [comment]
@reckter Yes, I will do a release tonight. Releases will be automated in the next couple of days, so it will be done faster and much more regularly. I'm focusing on spending time this week to do a big cleanup and make the project on the right path. Changelogs will also be generated automatically :)

**Comment by nicolashenry** [comment]
@thedaviddias Can you release it as `0.12.1`? :)

**Comment by thedaviddias** [comment]
I will probably do it over the weekend, just need to reword #378 and we should be good for a new release!

**Pull request merged**
