### PR TITLE
feat: added attr-no-unnecessary-whitespace rule

### PR DESCRIPTION
**Pull request by jakewtaylor**
Shows an error like:
`The attribute 'name' must not have spaces between the name and value.`
for code like:
```
type = "text"
type ="text"
type= "text"
```
This is valid:
```
type="text"
```

### CODE REVIEW

**Comment by jakewtaylor** [comment]
I've also added support for PHP files.

Anything between `<?php`/`<?` and `?>` tags is stripped out and replaced with newlines.

I've added a test to check that PHP is properly ignored.

**Comment by jakewtaylor** [comment]
Not really sure how to fix the coverage check failing - let me know how to get that to pass and I'll fix.

**Comment by Shinigami92** [comment]
Since `lib/htmlhint.js` is irrelevant to the current development phase, I think it is safe to merge this and bring it into the 'develop' branch

**Comment by thedaviddias** [comment]
Closing this old PR, reopened in #385 to speed up fixing merge conflicts.

**Pull request closed without merging**
