### PR TITLE
doc: Added doc missing rules

### LINKED ISSUE #698: Not all the rules are in the documentation
**Is your feature request related to a problem? Please describe.**
Not all the rules are in the documentation.

The rules that aren't in [_List of rules_](https://htmlhint.com/docs/user-guide/list-rules):
- `attr-sorted`
- `attr-value-single-quotes`
- `attr-whitespace`
- `html-lang-require`
- `script-disabled`
- `tagname-specialchars`

The rules that aren't in _Individual rules_ (menu):
- `attr-no-unnecessary-whitespace`
- `attr-sorted`
- `attr-value-single-quotes`
- `attr-whitespace`
- `doctype-html5`
- `html-lang-require`
- `input-requires-label`
- `script-disabled`
- `tag-self-close`
- `tagname-specialchars`
- `tags-check`

**Describe the solution you'd like**
Add all the rules in the documentation.

### PR DESCRIPTION
**Pull request by 8ctopus**
Partially fixes #698 (does not implement the pages)

### CODE REVIEW

**Comment by nschonni** [comment]
Thanks! I used your baseline list of the missing ones to start creating the missing pages in https://github.com/htmlhint/HTMLHint/pull/836

**Review by thedaviddias — APPROVED** [review]

**Comment by thedaviddias** [comment]
> Partially fixes #698 (does not implement the pages)

Thanks @8ctopus, please add `docs:` in front of the title of the PR.

**Comment by 8ctopus** [comment]
@thedaviddias something else missing?

**Comment by coliff** [comment]
I don't think this should be merged as it is. The first two rules added to the file are already present now (https://htmlhint.com/docs/user-guide/list-rules) - and the remaining rules which have been added show and error since the page hasn't been added- e.g. https://htmlhint.com/docs/user-guide/rules/tagname-specialchars

**Comment by nschonni** [comment]
Thanks @8ctopus! I added the actual documentation pages in https://github.com/htmlhint/HTMLHint/pull/889 instead

**Pull request closed without merging**
