### PR TITLE
fix(htmlhint.ts): replace deprecated request module with what-wg fetch

### PR DESCRIPTION
**Pull request by darcyparker**
***Short description of what this resolves:***
Replaces the deprecated request module with fetch.

Today, `npm install ` warns:

```bash
request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
(`uuid` is a dependency of `request`)

***Proposed changes:***

* Remove `request` and `@types/request`
* Replace with [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

Although `fetch` has a more modern async interface, I did not change the interface of `htmlUrl()`.  `htmlUrl()` and other fns could be reworked to use more modern async patterns in the future.  My main objective is to replace the deprecated `request` API.

### CODE REVIEW

**Comment by stuartbale** [comment]
Please link this pull request to the issue raised here:
https://github.com/htmlhint/HTMLHint/issues/645

**Comment by stuartbale** [comment]
@darcyparker - this fix appears to have stalled, i think because by the time it was reviewed there are conflicts. I wonder if you could spare the time to resolve the conflicts and do another pull request to get some movement on this?
Regards,
Stuart

**Comment by darcyparker** [comment]
@stuartbale - Yes, at the time of review, the `package-lock.json` had changed...  I just rebased.

**Comment by coliff** [comment]
build/test is failing - can you take a look @thedaviddias @darcyparker ?

**Comment by darcyparker** [comment]
@coliff - I am looking at it now.

**Comment by darcyparker** [comment]
The build/test issue was node-fetch v3.  Because this repo builds commonjs, I needed to use v2. (https://github.com/node-fetch/node-fetch#loading-and-configuring-the-module)  v3 is only 15 days old (as of now)... so I missed this when I rebased and reinstalled node-fetch.  I believe the tests will pass now.

**Comment by darcyparker** [comment]
FYI: I added node-fetch types for v2 as dev dependency.

**Comment by thedaviddias** [comment]
> FYI: I added node-fetch types for v2 as dev dependency.

Thanks for doing that work @darcyparker 🙏

**Review by thedaviddias — APPROVED** [review]

**Pull request merged**
