### PR TITLE
Migrate to Webpack & ES6 modules

### PR DESCRIPTION
**Pull request by Neo-Zhixing**
**Fixes**: #277 

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will not fail unit test.
- [ ] Check your code additions will not fail code linting checks.
Indentation was intentionally kept the way it originally was to minimize changes. Automatic formatting could be done at some point in the future.

#### Short description of what this resolves:
Removed Grunt and enabled Webpack
Migrate the code base to use ES6 modules

#### Proposed changes:
Further refactor the code base and progressively make everything ES6

### CODE REVIEW

**Comment by Neo-Zhixing** [comment]
Currently the bundled umd module has a size of more than 600KB. Work is needed to eliminate some of the dependencies from the build.

**Comment by Arcanemagus** [comment]
This _completely_ broke the Node.js API, with no changelog entry, no release notes on the release, and most importantly no update to the documentation.

It looks like now the `HTMLHint` being exported is a `Class` instead of a function, meaning we need to instantiate it.
Before and [the documentation](https://github.com/htmlhint/HTMLHint/wiki/Usage#javascript-with-node):
```js
var HTMLHint  = require("htmlhint").HTMLHint;
var messages = HTMLHint.verify('<ul><li></ul>', {'tag-pair': true});
```

Now:
```js
var HTMLHintClass  = require("htmlhint").HTMLHint;
var HTMLHint = new HTMLHintClass();
var messages = HTMLHint.verify('<ul><li></ul>', {'tag-pair': true});
```

However this appears to return an empty array no matter what I feed it, so something else has changed as well.

Breaking changes are okay as long as they are clearly communicated, this is an example of how not to do them.

**Comment by thedaviddias** [comment]
Hi @Arcanemagus, thanks to point that out, we were planning to fix these issues after the weekend where students worked on the project during Hackillinois.

We communicated on the discord channel about but be sure another release will be done in the next days to fix that.

It was an opportunity for students to work on open-source projects and yes, it comes with mistakes but we were aware of that. Thanks again.

**Comment by Arcanemagus** [comment]
Glad to hear it! I'll check back when https://github.com/AtomLinter/linter-htmlhint/pull/197 updates 😉.

**Comment by thedaviddias** [comment]
By the way, they won the prize for "the best contribution to a code review tool" 🙌

**Comment by Arcanemagus** [comment]
Reminder that the currently released version of the package is still broken 😉.

**Comment by Arcanemagus** [comment]
The currently released version (v0.11.0) is still broken.

**Comment by Arcanemagus** [comment]
The current release still hasn't been fixed, or the documentation updated to match whatever the new behavior is. 🤷‍♂

**Comment by Arcanemagus** [comment]
For anyone else coming to this, it looks like this is the new way to get a working `HTMLHint.verify`:
```js
const htmlhintModule = require('htmlhint');
const HTMLHint = new htmlhintModule.HTMLHint();
Object.keys(htmlhintModule.HTMLRules).forEach((rule) => {
  HTMLHint.addRule(htmlhintModule.HTMLRules[rule]);
});
```

Taken from the code used here to generate what you get at [`require('htmlhint').default`](https://github.com/htmlhint/HTMLHint/blob/fbb772d390d9100d8c8313c0739831a27c63a23e/src/core.js#L145-L149).

**Pull request merged**
