### PR TITLE
Adding support for custom RegExp in id-class-value rule

### LINKED ISSUE #122: id-class-value should accept a RegExp so it can be customized
For people using BEM syntax and similar.
Something like:

``` json
{
  "id-class-value" : "My regexp"
}
```

### PR DESCRIPTION
**Pull request by molant**
Fixes #122

### CODE REVIEW

**Comment by yaniswang** [comment]
Can you show your case?
Why add this feature?

**Comment by molant** [comment]
In our case we are using BEM notation for CSS and I wanted to enforce our style.

**Comment by yaniswang** [comment]
Can you show your code sample?

**Comment by molant** [comment]
For now we are using the following regex `"^([_\\-a-z\\d])*$"` while we clean up the code (everything lower case, number, no extended characters, _ and -).
Once we've finished our analysis of the code we will use a more strict regex to enforce the number of `-`, etc. like the ones generated by https://giacomozinetti.github.io/bemex/

**Comment by kaelig** [comment]
Nice, I'd love this feature to make it into HTMLHint too.

**Comment by kaelig** [comment]
@yaniswang is this package still maintained?

@molant have you published your fork on npm? The feature in this PR would be useful to a project I'm working on at the moment.

**Comment by molant** [comment]
@kaelig I haven't published to NPM. I think that @yaniswang did some changes that I haven't pull in my [fork](https://github.com/molant/HTMLHint).

**Comment by Shinigami92** [comment]
@molant we have revived this repo, sorry for the long wait

do you think there are other regex that could be useful
otherwise, I think about introducing a rule specific to the BEM notation

**Comment by molant** [comment]
@Shinigami92 I think that as long as the user has the possibility to use a regex things should be fine. There are many weird cases and notations out there...
Happy to see this repo revived!

**Comment by maartenbrakkee** [comment]
This would be nice to have, any ETA for v0.11.0 @thedaviddias ?

**Comment by thedaviddias** [comment]
Closing the PR as the support for custom RegExp was deployed in the last release.

**Pull request closed without merging**
