### PR TITLE
[WIP] Rewrite configuration structure

### PR DESCRIPTION
**Pull request by Shinigami92**
**Fixes**: #279 

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:

This will be a complete rewrite so the given configuration can provide more features
_Status: Work in progress_

#### Proposed changes: see #279

### CODE REVIEW

**Comment by nebulousdog** [comment]
looking forward to this!

**Comment by Shinigami92** [comment]
@nebulousdog Yes me too, but that must happen in a new PR
We have made a few changes that have caused a bit of chaos here XD

In addition, a few other things must be implemented beforehand so as not to create more chaos in the branches

Therefore, I'm just waiting for @thedaviddias to implement these changes

**Comment by nebulousdog** [comment]
@Shinigami92 sounds good! thanks for the update

**Comment by nebulousdog** [comment]
@thedaviddias any thoughts?

**Comment by Shinigami92** [comment]
I will recreate and work on this later
Closing for now

**Pull request closed without merging**
