### PR TITLE
feat: display warning log message when it can not parse config

### LINKED ISSUE #662: `.htmlhintrc` silently ignored if not valid JSON
If the `.htmlhintrc` is not valid JSON, the linter silently ignores it and uses a default config.

For example, I had made the mistake of keeping a trailing comma:

    {
        "attr-lowercase": false,
    }

The default config has `"attr-lowerclase": true` and I received a lot of unwanted errors. It took me a while to figure out that the malformatted JSON was the culprit.

It would be helpful if the linter at least displayed a warning log message upon execution if it cannot parse the config file.

### PR DESCRIPTION
**Pull request by is2ei**
fix #662

***Short description of what this resolves:***
This PR changes it to display a warning log message when it can not parse config.

***Proposed changes:***
Display warning log message

Screen Shot 2022-01-31 at 1 50 24

### CODE REVIEW

**Comment by is2ei** [comment]
Sorry, I would fix tests.

**Comment by is2ei** [comment]
Tests are fixed. Could you review it?

**Comment by is2ei** [comment]
@thedaviddias 
Hi, would this change be acceptable? If not, I'll close this PR.

**Review by thedaviddias — APPROVED** [review]

**Review by thedaviddias — APPROVED** [review]

**Comment by coliff** [comment]
@thedaviddias you approved this so can it be merged ?

**Comment by thedaviddias** [comment]
> @thedaviddias you approved this so can it be merged ?

Yes, it can. @is2ei Can you just fix the conflict?

**Comment by is2ei** [comment]
@thedaviddias 

I fixed the conflict.
The test below fails, but I'm not sure it relates to this change.
https://github.com/htmlhint/HTMLHint/runs/7480344654?check_suite_focus=true

**Pull request merged**
