### PR TITLE
chore(deps-dev): bump rollup packages

### PR DESCRIPTION
**Pull request by thedaviddias**
***Short description of what this resolves:***

Bump rollup packages

### CODE REVIEW

**Review by nschonni — APPROVED** [review]

**Comment by nschonni** [comment]
Noticed this not installing on the default branch `rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.`

**Comment by thedaviddias** [comment]
> Noticed this not installing on the default branch `rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.`

Good catch, gonna update it then.

**Comment by thedaviddias** [comment]
@nschonni removed it as it's not used

**Review by coliff — APPROVED** [review]

**Pull request merged**
