### PR TITLE
feat: adds button type rule

### LINKED ISSUE #157: button type
This is an enhancement request to add a warning when a button element is inside a form and does not have a set type attribute.

As you may already know, if a `<button>` does not have a set or invalid `type` attribute, the type defaults to `submit` ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)). Activating that button will submit the form and may not produce the desired effect.

### PR DESCRIPTION
**Pull request by marook**
should fix #157

### CODE REVIEW

**Comment by Shinigami92** [comment]
We should define an additional test:
`describe -> it -> 'type be not given on button should result in an ???'`
```js
var code = '<button />';
var messages = HTMLHint.verify(code, ruleOptions);
expect(messages.length).to.be(_); // 0 or 1?
```

I think it's better not to give a message in this case, because in frameworks like Angular, you often do not pass a type and treat it with a `(click)`-event

If you want to verify that `type` is passed to `<button />`, it should be a separate rule
Maybe that would be useful for `<input />`

**Comment by thedaviddias** [comment]
@Shinigami92 @marook any comments on this PR?

**Comment by Shinigami92** [comment]
I wrote a statement already above https://github.com/htmlhint/HTMLHint/pull/208#issuecomment-416044238

IMO we should try to add a rule named `attr-require-type` and this may take the values `false`, `true`, `'button'`, `'input'` or `['button', 'input']` (where the last ist the same as `true`)

`attr-` because very many existing rules use this prefix already  
`require-` becuase this word is also used in two existing rules already (alt- and titel- require)  
`type` because that's what it is 🙂

---

Why may wait around 2 weeks for the PR owner @marook to respond  

If this will not happen, we may think about to 
**merge it** and rebuild it for our purposes 
or 
**not merge it** and rebuild it from our site

**Comment by marook** [comment]
Sorry for my late reply. I don't use htmlhint anymore. Reading the comments I think going towards a generic solution for checking the existence of certain attributes on certain elements like it was described in this thread would be a feasible solution. This makes my pull request unnecessary.

**Comment by Shinigami92** [comment]
> Sorry for my late reply. I don't use htmlhint anymore. Reading the comments I think going towards a generic solution for checking the existence of certain attributes on certain elements like it was described in this thread would be a feasible solution. This makes my pull request unnecessary.

@marook Thanks for your response
One last thing I want to ask you: Did you switched to another linter/hinter? Or are you using e.g. `pug` right now? Or maybe you aren't working with HTML at all anymore?

Also I think I will takeover this task and copy some parts of your PR

**Comment by marook** [comment]
> One last thing I want to ask you: Did you switched to another linter/hinter? Or are you using e.g. `pug` right now? Or maybe you aren't working with HTML at all anymore?
My current projects don't fit well with a HTML hinter. If this changes in the future I think i will use HTMLHint again.

**Pull request closed without merging**
