### PR TITLE
wait for node to finish writing to stdout before exiting

### PR DESCRIPTION
**Pull request by admosity**
It appears that the exit signal is fired before the entire stdout stream is flushed. This causes issues for editors/IDEs that listen for the process exit event (atom in my case):

Using this atom package: https://github.com/AtomLinter/linter-htmlhint

image

Early end of input:
image

Slapped on a quick fix to listen for the drain event for json (as that's what is used in the linter I am using).

### CODE REVIEW

**Comment by admosity** [comment]
I realized that this is not going to work because this has been switched over to streams. On the previous version, I hooked into formatResult. You're going to need a more complete solution across all the formatters.

**Comment by admosity** [comment]
Re-opening for exposure.

**Comment by yaniswang** [comment]
What's your node version?

**Comment by admosity** [comment]
It's version 0.12.7. I'm still doing some digging as to what exactly is causing this.

**Comment by yaniswang** [comment]
In my case, exit signal after stdout, node version is v4.2.2

**Comment by admosity** [comment]
In my test the process exit event comes before the stdout close event.
However I was able to pull out all the data. As per the node child process
docs. The exit event doesn't mean that the stdout stream is finished. This
leads me to think that there is an issue with atom itself when an child
process exit event is received, because I saw the truncation of the stream
happen there when it didn't happen in similar code I had.

That being said, using the callback from the write call to stdout to ensure
the stream is flushed does fix the issue with the linter I was using. Check
the gist I have from the other referenced issue, I'd link it but I'm on my
phone. I have a quick fix for the json format which the linter uses.

**Comment by admosity** [comment]
I've added a more complete solution across all the formatters.

**Comment by yaniswang** [comment]
Can you show a demo code to match this issue?

**Comment by admosity** [comment]
https://github.com/admosity/HTMLHint/blob/exit-test-case/test/executable.spec.js

The test I added is kind of spotty. I've gotten it to fail once on v0.9.12. It fails pretty consistently on atom:
image

And here it's working with the current pull request:
image

**Comment by yaniswang** [comment]
@admosity can you upgrade your node to new version?

**Comment by yaniswang** [comment]
https://github.com/yaniswang/HTMLHint/commit/11d10aa980ce9a5e9f49a567341b8498bfb43b8e

I add the executable.spec tese case, and it run successed!

**Pull request closed without merging**
