### PR TITLE
feat: input-requires-label - All inputs require a label

### PR DESCRIPTION
**Pull request by olore**
This is for accessibility. 

Some references:
- https://www.w3.org/WAI/tutorials/forms/instructions/
- http://webaim.org/techniques/forms/controls

### CODE REVIEW

**Comment by olore** [comment]
I tried to fix the conflict, but because the version in the package.json is now `0.0.0-development` the `grunt` command is generating `lib/htmlhint.js` with that version, which I'm guessing we don't want to deliver.

I think package.json version needs to change, should I change it in this PR ?

**Comment by thedaviddias** [comment]
Hi @olore, I'm actually working on that. I'll publish an update in the next hour.

**Comment by olore** [comment]
I just saw https://github.com/thedaviddias/HTMLHint/issues/259 and now I'm up to speed. Thanks for reviving this project!

**Comment by thedaviddias** [comment]
You're welcome @olore, don't hesitate to join the discord channel to exchange about the project!

**Comment by thedaviddias** [comment]
@olore do you want to solve the merge conflict or do you want me to fix this in a new PR?

**Comment by Shinigami92** [comment]
@olore 💪❤

**Pull request merged**
