### PR TITLE
chore: add website deployment CI

### PR DESCRIPTION
**Pull request by nschonni**
***Short description of what this resolves:***
Copied from https://github.com/marketplace/actions/gh-pages-deploy, but not tested

***Proposed changes:***

### CODE REVIEW

**Comment by nschonni** [comment]
Not sure if this should filter the paths so only when something in the `website/` path is changed, but right now it would re-push each time

**Comment by thedaviddias** [comment]
> _**Short description of what this resolves:**_ Copied from https://github.com/marketplace/actions/gh-pages-deploy, but not tested
> 
> _**Proposed changes:**_

The deployment is handle by Netlify so we don't need a github action to deploy it to GH pages.

**Comment by nschonni** [comment]
I noticed that Netlify was used for deploying https://github.com/htmlhint/htmlhint-playground, but I didn't see that it was deploying the rest

**Comment by nschonni** [comment]
I was going to remove the playground folder after, to just leave Netlify to deploy that part separately

**Comment by thedaviddias** [comment]
> I was going to remove the playground folder after, to just leave Netlify to deploy that part separately

I need to double check why I did this way but I'm pretty I have a reason why the playground is setup this way. Let me get back to you on this.

**Pull request closed without merging**
