### PR TITLE
refactor: use `path.sep` simplify #443

### PR DESCRIPTION
**Pull request by fisker**
***Short description of what this resolves:***

Simplify `sep` replace

Ref: https://github.com/htmlhint/HTMLHint/pull/443#issuecomment-650074634

***Proposed changes:***

### CODE REVIEW

**Comment by fisker** [comment]
Why assign?

**Comment by Shinigami92** [comment]
You are the person who worked on this PR 🙂
Nothing more behind this

**Comment by Shinigami92** [comment]
damnd 😫
accidentally merged this into `master` instead of `beta`

**Pull request merged**
