### PR TITLE
test: add tests for HTML entities

### PR DESCRIPTION
**Pull request by rbanffy**
Add tests for checking & and HTML entities

### CODE REVIEW

**Comment by waldyrious** [comment]
@rbanffy the world needs more people like you. Just sayin :)

**Comment by rbanffy** [comment]
@waldyrious we should thank whoever fixes my tests now ;-)

**Comment by Shinigami92** [comment]
I think that can be merged and the change to `package.json` can be ignored as we will be updating all dependencies anyway

But we should check later if something like this will work
```html
<p>{{ a === 1 && b === 2 ? 'c' : 'd' }}</p>
```

**Comment by rbanffy** [comment]
It'll take me some time to drop the package.json changes. Feel free to move ahead without them.

I'm more concerned with the failing tests. Those I'm not sure how to fix.

**Comment by thedaviddias** [comment]
Closing this old PR, re-creating it #386

**Pull request closed without merging**
